AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Kittens Carousel
  Static Website Application
Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

Resources:
  KittensProject:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId

      InstanceType: t2.micro

      KeyName: firstkey

      SecurityGroups:
        - !Ref kittenscr

      Tags:
        - Key: Name
          Value: Web Server of StackName

      UserData:
        Fn::Base64:
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd wget
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 755 /var/www/html/
          wget https://raw.githubusercontent.com/plnknr/My_New_Projects/main/static-web/index.html
          wget https://raw.githubusercontent.com/plnknr/My_New_Projects/main/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/plnknr/My_New_Projects/main/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/plnknr/My_New_Projects/main/static-web/cat2.jpg

  kittenscr:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: accessible via web browser from anywhere.

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
